name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Python 3.5

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
          architecture: x64
      - name: Check pip
        run: pip --version
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install pipenv
        run: pip install pipenv
      - name: pipenv install (Py3.5)
        run: pipenv --bare install --dev --skip-lock
      - name: flake8 tests
        run: make flake8
      - name: Integration tests
        run: make integration-tests
      - name: Config environment variables tests
        run: make env-test
      - name: Unit tests
        run: make unit-test
      - name: Network logger tests
        run: make network-test
      - name: Upload to codecov
        run: pipenv run codecov
